version: "1.0"
info:
  model: int-scaffold
packages:
- name: NamanEdgeProject
  gitServerName: Naman_SAG_edge
  gitUrl: https://github.com/namanmolri/NamanEdgeProject
  gitUsername: namanmolri
  gitBranch: main
- name: NamanEdgeSourceControl
  gitServerName: Naman_SAG_edge
  gitUrl: https://github.com/namanmolri
  gitUsername: namanmolri
  gitBranch: main
services:
- serviceName: project.namanedge.integrations:Github_test_DAFS
  packages:
  - name: NamanEdgeProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.namanedge.integrations:random
  packages:
  - name: NamanEdgeProject
    version: "1.0"
- serviceName: pub.math:randomDouble
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.namanedge.integrations:githubSourceControl_test
  packages:
  - name: NamanEdgeProject
    version: "1.0"
  - name: NamanEdgeSourceControl
    version: "1.0"
- serviceName: test_github:github_flow_test
  packages:
  - name: NamanEdgeSourceControl
    version: "1.0"
